site_name: Open Stage Control
repo_name: open-stage-control
repo_url: https://github.com/jean-emmanuel/open-stage-control
edit_uri: tree/master/resources/docs/
copyright: "Open Stage Control is an <a href='http://ammd.net'>AMMD</a> software licensed under the <a href='https://github.com/jean-emmanuel/open-stage-control/blob/master/LICENSE'>GNU/GPLv3</a> License"
site_description: "Libre and modular OSC / MIDI controller"

theme:
    name: null
    custom_dir: 'theme/'
    favicon: 'img/logo-nobadge.png?1'
    include_search_page: true
    static_templates:
      - 404.html


extra:
    screenshot: img/ardour-osc.png
    links:
        -
            title: Download
            url: https://github.com/jean-emmanuel/open-stage-control/releases
            primary: true
        -
            title: Try online (requires chromium 50+)
            url : http://openstagecontrol.herokuapp.com

nav:
    - Open Stage Control: index.md
    - Docs: docs.md
    - Docs:
        - Getting started: docs/getting-started.md
        - User interface: docs/interface.md
        - Editing sessions: docs/editing-sessions.md
        - Widgets reference: docs/widgets-reference.md
        - Advanced property syntax: docs/advanced-property-syntax.md
        - Scripting: docs/scripting.md
        - CSS Tips: docs/css-tips.md
        - Theming: docs/theming.md
        - URL options: docs/url-options.md
        - Remote control: docs/remote-control.md
        - Custom module: docs/custom-module.md
        - Midi: docs/midi.md
        - Examples: docs/examples.md
        - Credits: docs/credits.md
    - Support: support.md

markdown_extensions:
    - markdown.extensions.extra
    - markdown.extensions.admonition
    - codehilite:
        guess_lang: False
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
        permalink: "#"
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

plugins:
    - search
